version: '2'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - ./data/config:/ql/config
      - ./data/log:/ql/log
      - ./data/db:/ql/db
      - ./data/scripts:/ql/scripts
      - ./data/repo:/ql/repo
      - ./data/raw:/ql/raw
      - ./data/deps:/ql/deps
    ports:
      - "0.0.0.0:1688:5700"
    restart: unless-stopped

  jdc:
    image: nolanhzy/nvjdc:latest
    volumes:
      - ./app:/app
      - ./etc/localtime:/etc/localtime:ro
    ports:
      - "0.0.0.0:1689:5700"
    restart: unless-stopped